services:
  db:
    image: postgres:15
    platform: linux/arm64/v8
    container_name: cinema_db
    restart: always
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema123
      POSTGRES_DB: cinema_app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
